# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ryne Mangum
title: Freelancer
email: rynemangum97@gmail.com
website: You are a here

# Dark Mode (true/false/never)
darkmode: false

# Social links

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ryne2.jpg
about_content: | # this will include new lines to allow paragraphs
  Aspiring Devops engineer with experience in developing websites using AWS cloud services, while integrating updates using GitHub, and python. I am always looking to expand my knowledge of new applications and best practices to find the reliable and fast solution to cloud based problems.

 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional Resume Website
        # link_text: Project Website
        additional_links:
          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Static Website hosted using AWS (S3, Cloudfront, and DynamoDB)
        description: | # this will include new lines to allow paragraphs
          Researched and implemented a static website using AWS S3 buckets for hosting and Cloudfront for Security. Using Javascript implemented a visitor counter that retrieved and stored its data from DynamoDB using AWS gateway for the API. Designed tests using python and SAM to deploy the new API resources. 

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amazon Web Services Cloud Practitioner
        # link_text: boringcompany.com
        caption: BWMDQ45L3B44Q233
        caption: Issued Jan 2022 - Expires Jan 2025

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: North Greenville University
        caption: 2015 - 2019
        sub_title: Bachelor of Education - BEd
        quote: >
          Pursued a Degree in Elementary Education
        description: | # this will include new lines to allow paragraphs
          Picked up many skills for communication, Public Speaking, and Presenting information. 
  - title: Skills
    layout: list
    content:
      - layout: top-right
        description: | # this will include new lines to allow paragraphs
          ***Cloud Skills***: AWS (EC2, S3, Lambda, API Gateway, DynamoDB, SQS)
          
          ***Containerization***: Docker / Kubernetes
          
          ***CI/CD***: Gitlab CI, AWS CodeDeploy, AWS CodePipeline
          
          ***Infrastructure as Code***: AWS SAM, CloudFormation
         
          ***Scripting***: Python, Java
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Teacher
        caption: Aug 2019 - Present
        sub_title: Spartanburg District Five Schools
        quote: >
        description: | # this will include new lines to allow paragraphs
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I spend my free time pursuing interest such as disk golfing, rock climbing, music, and history.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
